import React from 'react'
import AboutUs from '../Componets/AboutUs'

export const metadata = {
  title: "About Us | Next.js",
  description: "Generated by create next app",
};

export default function page() {
    return (
        <div>
            <AboutUs />
        </div>
    )
}
